version: '3.7'

services:
  grpc-test-web:
    build:
      context: .
      target: grpc-test-web
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000/
    ports:
      - "5000:5000"

  grpc-test-grpc:
    build:
      context: .
      target: grpc-test-grpc
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:50051/
    ports:
      - "50051:50051"